-- Migration to add complementary information fields to funcionarios table

ALTER TABLE ponto.funcionarios
ADD COLUMN nome_social VARCHAR(255),
ADD COLUMN unidade_trabalho VARCHAR(255),
ADD COLUMN tipo_contratacao VARCHAR(100),
ADD COLUMN cargo_funcao VARCHAR(150),
ADD COLUMN carga_horaria VARCHAR(50),
ADD COLUMN turno_trabalho VARCHAR(50), -- Diurno, Noturno, Revezamento
ADD COLUMN data_admissao DATE,
ADD COLUMN data_exercicio DATE,
ADD COLUMN endereco VARCHAR(255),
ADD COLUMN endereco_numero VARCHAR(20),
ADD COLUMN endereco_complemento VARCHAR(100),
ADD COLUMN endereco_cep VARCHAR(20),
ADD COLUMN endereco_bairro VARCHAR(100),
ADD COLUMN endereco_municipio VARCHAR(100),
ADD COLUMN endereco_uf CHAR(2),
ADD COLUMN telefone_fixo VARCHAR(20),
ADD COLUMN endereco_email VARCHAR(150),
ADD COLUMN naturalidade VARCHAR(100),
ADD COLUMN naturalidade_uf CHAR(2),
ADD COLUMN data_nascimento DATE,
ADD COLUMN estado_civil VARCHAR(50),
ADD COLUMN nacionalidade VARCHAR(100),
ADD COLUMN sexo VARCHAR(50),
ADD COLUMN raca_cor VARCHAR(50),
ADD COLUMN deficiencia BOOLEAN DEFAULT FALSE,
ADD COLUMN deficiencia_tipo VARCHAR(100),
ADD COLUMN deficiencia_cid VARCHAR(20),
ADD COLUMN tipo_sanguineo VARCHAR(20),
ADD COLUMN escolaridade VARCHAR(150),
ADD COLUMN pis_pasep VARCHAR(50),
ADD COLUMN carteira_conselheiro VARCHAR(100),
ADD COLUMN rg_numero VARCHAR(50),
ADD COLUMN rg_orgao VARCHAR(50),
ADD COLUMN rg_data_emissao DATE,
ADD COLUMN cnh_numero VARCHAR(50),
ADD COLUMN cnh_categoria VARCHAR(10),
ADD COLUMN cnh_validade DATE,
ADD COLUMN titulo_eleitor_numero VARCHAR(50),
ADD COLUMN titulo_eleitor_zona VARCHAR(10),
ADD COLUMN titulo_eleitor_secao VARCHAR(10),
ADD COLUMN reservista_numero VARCHAR(50),
ADD COLUMN reservista_serie VARCHAR(10),
ADD COLUMN ctps_numero VARCHAR(50),
ADD COLUMN ctps_serie VARCHAR(20),
ADD COLUMN ctps_data_emissao DATE,
ADD COLUMN ctps_uf CHAR(2),
ADD COLUMN nome_pai VARCHAR(255),
ADD COLUMN nome_mae VARCHAR(255),
ADD COLUMN nome_conjuge VARCHAR(255),
ADD COLUMN nacionalidade_conjuge VARCHAR(100),
ADD COLUMN naturalidade_conjuge VARCHAR(100),
ADD COLUMN naturalidade_uf_conjuge CHAR(2),
ADD COLUMN data_nascimento_conjuge DATE,
ADD COLUMN filhos_menores JSONB, -- Array of objects
ADD COLUMN dependentes_ir JSONB, -- Array of objects
ADD COLUMN banco_nome VARCHAR(100),
ADD COLUMN banco_agencia VARCHAR(20),
ADD COLUMN banco_conta VARCHAR(50),
ADD COLUMN observacoes_complementares TEXT;
